title: Portafolio Matías Espinoza
description: Este portafolio muestra la progresión del aprendizaje en el curso de Front-End, lograda a través del caso de construcción de un sitio para un hospital.
show_downloads: false
google_analytics:
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
