title: Portafolio Matías Espinoza
description: Este portafolio muestra la progresión de conocimientos en Front-End lograda a traves del caso de construcción de un sitio para un hospital.
show_downloads: false
google_analytics:
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
